version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  client:
    build: ./clientGo
    ports:
      - "5050:5050"
    networks:
      testing_net:
        ipv4_address: 172.28.1.5
  
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16